/** Statistical, summary-only concept drift monitoring for fraud calibration. */
import { config } from '../config';
export type DriftMethod = 'ks' | 'psi' | 'chiSquared';
export type DriftType = 'NONE' | 'VIRTUAL' | 'REAL';
export type DriftPattern = 'NONE' | 'SUDDEN' | 'GRADUAL';
export type DriftSeverity = 'NONE' | 'LOW' | 'MEDIUM' | 'HIGH';
export interface FraudDriftObservation { timestamp: Date; label?: 0 | 1; numeric?: Record<string, number | null | undefined>; categorical?: Record<string, string | null | undefined>; }
export interface FeatureDriftResult { feature: string; method: DriftMethod; driftDetected: boolean; pValue?: number; psi?: number; statistic: number; sampleSize: number; }
export interface LabelDriftResult { driftDetected: boolean; pValue: number; baselineRate: number; currentRate: number; baselineSampleSize: number; currentSampleSize: number; }
export interface DriftReport { driftDetected: boolean; driftType: DriftType; driftPattern: DriftPattern; affectedFeatures: string[]; severity: DriftSeverity; recommendedAction: 'NONE' | 'RECALIBRATE' | 'ALERT'; featureResults: FeatureDriftResult[]; labelResult?: LabelDriftResult; detectedAt: Date; baselineId?: string; modelVersionId?: string; }
export interface NumericBaseline { edges: number[]; counts: number[]; sampleSize: number; }
export interface CategoricalBaseline { counts: Record<string, number>; sampleSize: number; }
export interface DriftBaseline { establishedAt: string; numeric: Record<string, NumericBaseline>; categorical: Record<string, CategoricalBaseline>; labels: { positives: number; sampleSize: number }; }
export interface FraudDriftConfig { enabled: boolean; methods: DriftMethod[]; significanceLevel: number; psiThreshold: number; minSamples: number; bins: number; baselineWindowHours: number; currentWindowHours: number; detectionIntervalMinutes: number; }
const defaults = (): FraudDriftConfig => { const c = (config as typeof config & { fraudDrift?: Partial<FraudDriftConfig> }).fraudDrift; return { enabled: c?.enabled ?? true, methods: c?.methods ?? ['ks','psi','chiSquared'], significanceLevel: c?.significanceLevel ?? .01, psiThreshold: c?.psiThreshold ?? .2, minSamples: c?.minSamples ?? 30, bins: c?.bins ?? 10, baselineWindowHours: c?.baselineWindowHours ?? 720, currentWindowHours: c?.currentWindowHours ?? 168, detectionIntervalMinutes: c?.detectionIntervalMinutes ?? 60 }; };
const normalCdf = (x: number) => { const t=1/(1+.2316419*Math.abs(x)),d=.3989423*Math.exp(-x*x/2),p=1-d*t*(.3193815+t*(-.3565638+t*(1.781478+t*(-1.821256+t*1.330274)))); return x>=0?p:1-p; };
export function kolmogorovSmirnovTest(baseline: number[], current: number[]) { if (!baseline.length || !current.length) return { statistic:0,pValue:1 }; const a=[...baseline].sort((x,y)=>x-y),b=[...current].sort((x,y)=>x-y); let i=0,j=0,d=0; while(i<a.length||j<b.length){const x=Math.min(i<a.length?a[i]:Infinity,j<b.length?b[j]:Infinity);while(i<a.length&&a[i]<=x)i++;while(j<b.length&&b[j]<=x)j++;d=Math.max(d,Math.abs(i/a.length-j/b.length));} const n=a.length*b.length/(a.length+b.length),l=(Math.sqrt(n)+.12+.11/Math.sqrt(n))*d; let p=0;for(let k=1;k<=100;k++){const q=2*(k%2?1:-1)*Math.exp(-2*k*k*l*l);p+=q;if(Math.abs(q)<1e-10)break;}return {statistic:d,pValue:Math.max(0,Math.min(1,p))}; }
export function populationStabilityIndex(expected:number[], actual:number[]) { const et=expected.reduce((a,b)=>a+b,0),at=actual.reduce((a,b)=>a+b,0); if(!et||!at||expected.length!==actual.length)return 0;return expected.reduce((s,e,i)=>{const ep=Math.max(e/et,1e-6),ap=Math.max(actual[i]/at,1e-6);return s+(ap-ep)*Math.log(ap/ep);},0); }
export function chiSquaredTest(expected:number[], observed:number[]) { const et=expected.reduce((a,b)=>a+b,0),ot=observed.reduce((a,b)=>a+b,0);if(!et||!ot||expected.length!==observed.length)return {statistic:0,pValue:1};const scale=ot/et;let statistic=0,df=0;for(let i=0;i<expected.length;i++)if(expected[i]*scale>=1e-9){statistic+=(observed[i]-expected[i]*scale)**2/(expected[i]*scale);df++;}if(df<=1)return {statistic,pValue:1};const k=df-1,z=((statistic/k)**(1/3)-(1-2/(9*k)))/Math.sqrt(2/(9*k));return {statistic,pValue:Math.max(0,Math.min(1,1-normalCdf(z)))}; }
const histogram=(values:number[],edges:number[])=>{const c=Array(Math.max(0,edges.length-1)).fill(0);for(const v of values){let x=edges.length-2;for(let i=0;i<edges.length-1;i++)if(v<=edges[i+1]){x=i;break;}if(x>=0)c[x]++;}return c;};
export class FraudDriftDetectionService {
 private readonly settings:FraudDriftConfig; private lastDriftAt?:Date; constructor(settings:Partial<FraudDriftConfig>={}){this.settings={...defaults(),...settings};}
 establishBaseline(observations:FraudDriftObservation[]):DriftBaseline { const n:Record<string,number[]>={},c:Record<string,Record<string,number>>={};let positives=0,count=0;for(const o of observations){if(o.label!==undefined){positives+=o.label;count++;}for(const[k,v]of Object.entries(o.numeric??{}))if(typeof v==='number'&&Number.isFinite(v))(n[k]??=[]).push(v);for(const[k,v]of Object.entries(o.categorical??{}))if(v){const x=c[k]??={};x[v]=(x[v]??0)+1;}}const numeric:Record<string,NumericBaseline>={};for(const[k,v]of Object.entries(n)){const min=Math.min(...v),max=Math.max(...v),w=max===min?1:(max-min)/this.settings.bins,e=Array.from({length:this.settings.bins+1},(_,i)=>min+i*w);e[e.length-1]=max;numeric[k]={edges:e,counts:histogram(v,e),sampleSize:v.length};}const categorical:Record<string,CategoricalBaseline>={};for(const[k,v]of Object.entries(c))categorical[k]={counts:v,sampleSize:Object.values(v).reduce((a,b)=>a+b,0)};return {establishedAt:new Date().toISOString(),numeric,categorical,labels:{positives,sampleSize:count}}; }
 detectFeatureDrift(b:DriftBaseline,obs:FraudDriftObservation[]):FeatureDriftResult[]{const r:FeatureDriftResult[]=[];for(const[f,s]of Object.entries(b.numeric)){const v=obs.map(o=>o.numeric?.[f]).filter((x):x is number=>typeof x==='number'&&Number.isFinite(x));if(s.sampleSize<this.settings.minSamples||v.length<this.settings.minSamples)continue;const currentCounts=histogram(v,s.edges),psi=populationStabilityIndex(s.counts,currentCounts),ks=kolmogorovSmirnovTest(s.counts.flatMap((count,index)=>Array(count).fill(index)),currentCounts.flatMap((count,index)=>Array(count).fill(index))),useKs=this.settings.methods.includes('ks');r.push({feature:f,method:useKs?'ks':'psi',statistic:useKs?ks.statistic:psi,pValue:useKs?ks.pValue:undefined,psi,sampleSize:v.length,driftDetected:(useKs&&ks.pValue<this.settings.significanceLevel)||(this.settings.methods.includes('psi')&&psi>=this.settings.psiThreshold)});}for(const[f,s]of Object.entries(b.categorical)){const c:Record<string,number>={};for(const o of obs){const v=o.categorical?.[f];if(v)c[v]=(c[v]??0)+1;}const keys=[...new Set([...Object.keys(s.counts),...Object.keys(c)])],n=Object.values(c).reduce((a,b)=>a+b,0);if(s.sampleSize<this.settings.minSamples||n<this.settings.minSamples)continue;const t=chiSquaredTest(keys.map(k=>s.counts[k]??.5),keys.map(k=>c[k]??0));r.push({feature:f,method:'chiSquared',statistic:t.statistic,pValue:t.pValue,sampleSize:n,driftDetected:this.settings.methods.includes('chiSquared')&&t.pValue<this.settings.significanceLevel});}return r;}
 detectLabelDrift(b:DriftBaseline,obs:FraudDriftObservation[]):LabelDriftResult|undefined{const l=obs.map(o=>o.label).filter((x):x is 0|1=>x!==undefined);if(b.labels.sampleSize<this.settings.minSamples||l.length<this.settings.minSamples)return;const p1=b.labels.positives/b.labels.sampleSize,pos=l.reduce((a,x)=>a+x,0),p2=pos/l.length,p=(b.labels.positives+pos)/(b.labels.sampleSize+l.length),se=Math.sqrt(p*(1-p)*(1/b.labels.sampleSize+1/l.length)),pv=se===0?1:2*(1-normalCdf(Math.abs(p2-p1)/se));return {driftDetected:pv<this.settings.significanceLevel,pValue:pv,baselineRate:p1,currentRate:p2,baselineSampleSize:b.labels.sampleSize,currentSampleSize:l.length};}
 classifyDrift(features:FeatureDriftResult[],label?:LabelDriftResult):Pick<DriftReport,'driftDetected'|'driftType'|'driftPattern'|'affectedFeatures'|'severity'|'recommendedAction'>{const affectedFeatures=features.filter(x=>x.driftDetected).map(x=>x.feature),driftDetected=affectedFeatures.length>0||!!label?.driftDetected,driftType:DriftType=!driftDetected?'NONE':label?.driftDetected?'REAL':'VIRTUAL';const rateShift=label?Math.abs((label.currentRate??0)-(label.baselineRate??0)):0;const driftPattern:DriftPattern=!driftDetected?'NONE':(rateShift>=0.1||affectedFeatures.length>=2)?'SUDDEN':'GRADUAL';const severity:DriftSeverity=!driftDetected?'NONE':driftType==='REAL'||affectedFeatures.length>1?'HIGH':'MEDIUM';return {driftDetected,driftType,driftPattern,affectedFeatures,severity,recommendedAction:driftType==='REAL'?'ALERT':driftType==='VIRTUAL'?'RECALIBRATE':'NONE'};}
 shouldTriggerRecalibration(report:DriftReport){return report.driftDetected&&report.driftType==='VIRTUAL'&&report.recommendedAction==='RECALIBRATE';}
 detect(b:DriftBaseline,obs:FraudDriftObservation[],context:Pick<DriftReport,'baselineId'|'modelVersionId'>={}):DriftReport{const featureResults=this.detectFeatureDrift(b,obs),labelResult=this.detectLabelDrift(b,obs);return {...this.classifyDrift(featureResults,labelResult),featureResults,labelResult,detectedAt:new Date(),...context};}
}
export default FraudDriftDetectionService;
